name: PROD | Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - feature/updating-pipeline
  pull_request:
    branches: main


  repository_dispatch:
    types: PROD_DEPLOY

env:
    HOST: app@${{ secrets.PROD_HOST_IP }}
    PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
    ENVIRONMENT: prod
    BACKEND_PORT: 5000
    FRONTEND_PORT: 3000

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build -t ${{ github.event.repository.name }}-$ENVIRONMENT . --no-cache
        docker save ${{ github.event.repository.name }}-$ENVIRONMENT > ${{ github.event.repository.name }}.tar
        ls -1

    - name: Saving docker image to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: |
          ${{ github.event.repository.name }}.tar
        retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Restoring docker image from artifacts
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Uploading artifact to the server
      run: |
        ls -1
        which rsync || ( apt-get update -y && apt-get install rsync -y )
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        eval $(ssh-agent -s)
        echo "${PRIVATE_SSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        ssh ${HOST} docker image rm -f $(docker images --filter=reference="${{ github.event.repository.name }}-${ENVIRONMENT}:*" -q) || true
        echo "${ENV_FILE}" > .env
        echo "${SA_FILE}" > sa.json
        git clone https://github.com/ALLATRA-IT/cloudobs-infrastructure.git --depth 1
        cp cloudobs-infrastructure/shared/files/docker-compose.yml .
        ls -1 docker-compose*
        printf "ENVIRONMENT=${ENVIRONMENT}\nBACKEND_PORT=${BACKEND_PORT}\nFRONTEND_PORT=${FRONTEND_PORT}" > .compose.env
        ssh ${HOST} "docker load --input ${{ github.event.repository.name }}.tar && mkdir -p ~/${ENVIRONMENT}"
        rsync -a -v --progress --delete --quiet sa.json .compose.env docker-compose.yml ${{ github.event.repository.name }}.tar ${HOST}:~/${ENVIRONMENT}/
        ssh ${HOST} "docker load --input ~/${ENVIRONMENT}/${{ github.event.repository.name }}.tar"
        ssh ${HOST} "docker compose down && docker compose --env-file ~/${ENVIRONMENT}/.compose-env up -d && sleep 10 && docker compose ps"
